packages:
  # Main application packages
  - 'brx-app'
  - 'brx-core'
  - 'brand-guidelines'
  
  # Shared packages and libraries
  - 'packages/*'
  
  # Development and tooling
  - 'dev_tools/*'
  - 'scripts/*'
  
  # Documentation
  - 'docs/*'
  
  # Exclude certain directories
  - '!**/test-results'
  - '!**/node_modules'
  - '!**/dist'
  - '!**/build'
  - '!**/.next'
