version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: brx-postgres
    restart: always
    environment:
      POSTGRES_USER: brx_user
      POSTGRES_PASSWORD: brx_password
      POSTGRES_DB: brx_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U brx_user -d brx_local"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: