#!/bin/bash

echo "🚀 BRX Claude Code Conversation Upload Setup"
echo "==========================================="
echo ""
echo "Your Pinecone API key has been retrieved from 1Password."
echo ""
echo "You need to provide your OpenAI API key. To find it:"
echo "1. Check 1Password for 'OpenAI API Key'"
echo "2. Or visit https://platform.openai.com/api-keys"
echo ""
echo "Run this command with your OpenAI API key:"
echo ""
echo "export OPENAI_API_KEY='your-api-key-here'"
echo "source venv/bin/activate"
echo "python upload-conversation.py"
echo ""
echo "Or run it all in one line:"
echo ""
echo "OPENAI_API_KEY='your-api-key-here' python upload-conversation.py"