name: brx-ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  PNPM_VERSION: '9'
  NODE_VERSION: '20'

jobs:
  install-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1Password → makes secrets available to later steps
      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v2
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      # (optional) load individual secrets as env vars
      - name: Load app secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          DATABASE_URL:  op://brx-ci/prod/DATABASE_URL
          NEXTAUTH_SECRET: op://brx-ci/prod/NEXTAUTH_SECRET

      - uses: pnpm/action-setup@v3
        with: { version: ${{ env.PNPM_VERSION }} }
      - uses: actions/setup-node@v4
        with: { node-version: ${{ env.NODE_VERSION }}, cache: pnpm }
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run type-check

  build:
    needs: install-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: ${{ env.PNPM_VERSION }} }
      - uses: actions/setup-node@v4
        with: { node-version: ${{ env.NODE_VERSION }}, cache: pnpm }
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build

# add more jobs later (e.g., playwright e2e, docker image) 
